#!/bin/sh

# Copyright (C) 2007 Segher Boessenkool <segher@kernel.crashing.org>
# Released under the terms of the GNU GPL, version 2


BDIR=$( (cd `dirname $0` ; pwd))
. $BDIR/config


fatal() {
	$ECHO -e "  \033[31mFAILED\033[0m"
	exit $1
}


mkdir kernel 2>/dev/null
( \
cd kernel && \
$ECHO -ne "    kernel:" && \
../../timert configure ../log-kernel-configure \
	make ARCH=$ARCH CROSS_COMPILE=$TARGET- \
	-C $KERNEL_SRC O=$PWD $DEFCONFIG && \
../../timert build ../log-kernel-build \
	make ARCH=$ARCH CROSS_COMPILE=$TARGET- $MAKEOPTS && \
	$ECHO -n "  " && \
	$ECHO -n $(grep -ci "warning:" ../log-kernel-build) && \
	$ECHO -n " warnings" \
) || fatal 103
