#!/bin/sh

# Copyright (C) 2007-2009 Segher Boessenkool <segher@kernel.crashing.org>
# Released under the terms of the GNU GPL, version 2


BDIR=$( (cd `dirname $0` ; pwd))
. $BDIR/config


fatal() {
	$ECHO -e "  \033[31mFAILED\033[0m"
	exit $1
}


mkdir binutils 2>/dev/null
( \
cd binutils && \
$ECHO -ne "  binutils:" && \
$BDIR/timert configure ../log-binutils-configure \
	$BINUTILS_SRC/configure --target=$TARGET --prefix=$PREFIX \
	--enable-64-bit-bfd --disable-nls --disable-werror \
	$EXTRA_BINUTILS_CONF && \
$BDIR/timert build ../log-binutils-build make $MAKEOPTS && \
$BDIR/timert install ../log-binutils-install make install && \
$ECHO \
) || fatal 101
