#!/bin/sh

# Copyright (C) 2007 Segher Boessenkool <segher@kernel.crashing.org>
# Released under the terms of the GNU GPL, version 2

BDIR=$( (cd `dirname $0` ; pwd))
source $BDIR/config


export PATH=$PREFIX/bin:$PATH


BUILD_TOOLCHAIN=yes
case $1 in
	--kernel) BUILD_TOOLCHAIN=no; shift ;;
esac

ARCH=$1
DEFCONFIG=${2:-defconfig}

case $ARCH in
	*-eabi)		TARGET=$ARCH ;;
	*-elf)		TARGET=$ARCH ;;

	avr32)		TARGET=avr-linux ;;
	blackfin)	TARGET=bfin-uclinux ;;
	h8300)		TARGET=h8300-elf ;;
	m68knommu)	TARGET=m68k-linux ;;
	mn10300)	TARGET=am33_2.0-linux ;;
	parisc)		TARGET=hppa-linux ;;
	parisc64)	TARGET=hppa64-linux ;;
	ppc)		TARGET=powerpc-linux ;;
	sh)		TARGET=sh3-linux ;;
	v850)		TARGET=v850e-linux ;;
	*)		TARGET=$ARCH-linux ;;
esac


echo "Building $ARCH... (target $TARGET)"
mkdir $ARCH 2>/dev/null
cd $ARCH

case $ARCH in
	mips64)		ARCH=mips ;;
	parisc64)	ARCH=parisc ;;
	powerpc64)	ARCH=powerpc ;;
	sh64)		ARCH=sh ;;
esac


export ARCH TARGET DEFCONFIG


case $BUILD_TOOLCHAIN in
	yes) $BDIR/build-binutils || exit 101;
	     $BDIR/build-gcc || exit 102;;
esac

$BDIR/build-kernel || exit 103
echo -e "  \e[32mOK\e[0m"
