#!/bin/sh

# Copyright (C) 2007 Segher Boessenkool <segher@kernel.crashing.org>
# Released under the terms of the GNU GPL, version 2


# Set these paths to the appropriate values for your local setup

# Where are the various source trees
BINUTILS_SRC=/home/segher/src/src
GCC_SRC=/home/segher/src/gcc
KERNEL_SRC=/home/segher/src/kernel

# Where to find the host mpfr library
MPFR=/opt/cfarm/mpfr-2.3.1

# Where to install the cross toolchains
PREFIX=/home/segher/cross

# Options for make
MAKEOPTS=-j4

# End of configuration section.


BUILD_TOOLCHAIN=yes
case $1 in
	--kernel) BUILD_TOOLCHAIN=no; shift ;;
esac

ARCH=$1
DEFCONFIG=${2:-defconfig}

case $ARCH in
	avr32)		TARGET=avr-linux ;;
	blackfin)	TARGET=bfin-uclinux ;;
	h8300)		TARGET=h8300-elf ;;
	m68knommu)	TARGET=m68k-linux ;;
	mn10300)	TARGET=am33_2.0-linux ;;
	parisc)		TARGET=hppa-linux ;;
	parisc64)	TARGET=hppa64-linux ;;
	ppc)		TARGET=powerpc-linux ;;
	sh)		TARGET=sh3-linux ;;
	v850)		TARGET=v850e-linux ;;
	*)		TARGET=$ARCH-linux ;;
esac


echo "Building $ARCH... (target $TARGET)"
mkdir $ARCH 2>/dev/null
cd $ARCH

case $ARCH in
	mips64)		ARCH=mips ;;
	parisc64)	ARCH=parisc ;;
	powerpc64)	ARCH=powerpc ;;
	sh64)		ARCH=sh ;;
esac


fatal() {
	echo -e "  \e[31mFAILED\e[0m"
	exit $1
}


binutils() {
mkdir binutils 2>/dev/null
( \
cd binutils && \
echo -ne "  binutils:" && \
../../timert configure ../log-binutils-configure \
	$BINUTILS_SRC/configure --target=$TARGET --prefix=$PREFIX && \
../../timert build ../log-binutils-build make $MAKEOPTS && \
../../timert install ../log-binutils-install make install && \
echo \
) || fatal 101
}


gcc() {
mkdir gcc 2>/dev/null
( \
cd gcc && \
echo -ne "       gcc:" && \
../../timert configure ../log-gcc-configure \
	$GCC_SRC/configure \
	--target=$TARGET --enable-targets=all --prefix=$PREFIX \
	--with-mpfr=$MPFR \
	--enable-languages=c --without-headers \
	--enable-sjlj-exceptions --with-system-libunwind \
	--disable-nls --disable-threads --disable-shared \
	--disable-libmudflap --disable-libssp --disable-libgomp \
	--disable-decimal-float \
	--enable-checking=yes,rtl && \
../../timert build ../log-gcc-build make $MAKEOPTS && \
../../timert install ../log-gcc-install make install && \
echo \
) || fatal 102
}
##	--enable-sjlj-exceptions --with-system-libunwind \


kernel() {
mkdir kernel 2>/dev/null
( \
cd kernel && \
echo -ne "    kernel:" && \
../../timert configure ../log-kernel-configure \
	make ARCH=$ARCH CROSS_COMPILE=$TARGET- \
	-C $KERNEL_SRC O=$PWD $DEFCONFIG && \
../../timert build ../log-kernel-build \
	make ARCH=$ARCH CROSS_COMPILE=$TARGET- $MAKEOPTS && \
	echo -n "  " && \
	echo -n $(grep -ci "warning:" ../log-kernel-build) && \
	echo -n " warnings" \
) || fatal 103
}


case $BUILD_TOOLCHAIN in
	yes) binutils; gcc ;;
esac

kernel
echo -e "  \e[32mOK\e[0m"
