#!/bin/sh

# Copyright (C) 2007 Segher Boessenkool <segher@kernel.crashing.org>
# Released under the terms of the GNU GPL, version 2


BDIR=$( (cd `dirname $0` ; pwd))
. $BDIR/config


fatal() {
	echo -e "  \e[31mFAILED\e[0m"
	exit $1
}


mkdir binutils 2>/dev/null
( \
cd binutils && \
echo -ne "  binutils:" && \
$BDIR/timert configure ../log-binutils-configure \
	$BINUTILS_SRC/configure --target=$TARGET --prefix=$PREFIX && \
$BDIR/timert build ../log-binutils-build make $MAKEOPTS && \
$BDIR/timert install ../log-binutils-install make install && \
echo \
) || fatal 101
