#!/bin/sh

# Copyright (C) 2007-2009 Segher Boessenkool <segher@kernel.crashing.org>
# Released under the terms of the GNU GPL, version 2


BDIR=$( (cd `dirname $0` ; pwd))
. $BDIR/config


fatal() {
	$ECHO -e "  \033[31mFAILED\033[0m"
	exit $1
}


mkdir gcc 2>/dev/null
( \
cd gcc && \
$ECHO -ne "       gcc:" && \
../../timert configure ../log-gcc-configure \
	$GCC_SRC/configure \
	--target=$TARGET --enable-targets=all --prefix=$PREFIX \
	--enable-languages=c --without-headers \
	--enable-sjlj-exceptions --with-system-libunwind \
	--disable-nls --disable-threads --disable-shared \
	--disable-libmudflap --disable-libssp --disable-libgomp \
	--disable-decimal-float --disable-libquadmath \
	--enable-checking=$CHECKING \
	$EXTRA_GCC_CONF && \
../../timert build ../log-gcc-build make $MAKEOPTS && \
../../timert install ../log-gcc-install make install && \
$ECHO \
) || fatal 102
