#!/bin/sh

# Copyright (C) 2007-2009 Segher Boessenkool <segher@kernel.crashing.org>
# Released under the terms of the GNU GPL, version 2

BDIR=$( (cd `dirname $0` ; pwd))
. $BDIR/config


$ECHO "================== Primary platforms ========================="
./build "$@" arm
./build "$@" mips
./build "$@" mips64 ip32_defconfig
./build "$@" powerpc ppc6xx_defconfig
./build "$@" powerpc64
./build "$@" sparc
./build "$@" sparc64
./build "$@" i386
./build "$@" x86_64
$ECHO "================== Secondary platforms ======================="
./build "$@" parisc
./build "$@" parisc64 a500_defconfig
./build "$@" ia64
./build "$@" s390
$ECHO "================== Tertiary platforms ========================"
./build "$@" alpha
./build "$@" avr32
./build "$@" blackfin
./build "$@" cris
./build "$@" frv
./build "$@" h8300
./build "$@" m32r
./build "$@" m68k
./build "$@" m68knommu
./build "$@" mn10300
./build "$@" score
./build "$@" sh
./build "$@" sh64 cayman_defconfig
./build "$@" xtensa
$ECHO "================== Imaginary platforms ======================="
./build "$@" microblaze
