#!/bin/sh

# Copyright (C) 2007-2017 Segher Boessenkool <segher@kernel.crashing.org>
# Released under the terms of the GNU GPL, version 2

BDIR=$( (cd `dirname $0` ; pwd))
. $BDIR/config


export PATH=$PREFIX/bin:$PATH


BUILD_BINUTILS=no
BUILD_GCC=no
BUILD_KERNEL=no
while :; do
	case $1 in
		--binutils)	BUILD_BINUTILS=yes; shift ;;
		--gcc)		BUILD_GCC=yes; shift ;;
		--kernel)	BUILD_KERNEL=yes; shift ;;
		--toolchain)	BUILD_BINUTILS=yes; BUILD_GCC=yes; shift ;;
		*) break
	esac
done
case $BUILD_BINUTILS$BUILD_GCC$BUILD_KERNEL in
	nonono)	BUILD_BINUTILS=yes;
		BUILD_GCC=yes;
		BUILD_KERNEL=yes
esac


ARCH=$1
DEFCONFIG=${2:-defconfig}

case $ARCH in
	*-*eabi*)	TARGET=$ARCH ;;
	*-elf)		TARGET=$ARCH ;;
	*-none)		TARGET=$ARCH ;;
	*-rtems*)	TARGET=$ARCH ;;
	*-linux*)	TARGET=$ARCH ;;

	arc)		TARGET=arc-elf ;;
	arm)		TARGET=arm-linux-gnueabi ;;
	arm64)		TARGET=aarch64-linux ;;
	blackfin)	TARGET=bfin-uclinux ;;
	c6x)		TARGET=c6x-elf ;;
	m68knommu)	TARGET=m68k-linux ;;
	mn10300)	TARGET=am33_2.0-linux ;;
	parisc)		TARGET=hppa-linux ;;
	parisc64)	TARGET=hppa64-linux ;;
	ppc)		TARGET=powerpc-linux ;;
	score)		TARGET=score-elf ;;
	sh)		TARGET=sh4-linux ;;
	shnommu)	TARGET=sh2-linux ;;
	tile)		TARGET=tilegx-linux ;;
	v850)		TARGET=v850e-linux ;;
	*)		TARGET=$ARCH-linux ;;
esac


$ECHO "Building $ARCH... (target $TARGET)"
mkdir $ARCH 2>/dev/null
cd $ARCH

case $ARCH in
	mips64)		ARCH=mips ;;
	parisc64)	ARCH=parisc ;;
	powerpc64)	ARCH=powerpc ;;
	riscv*)		ARCH=riscv ;;
	shnommu)	ARCH=sh ;;
esac


export ARCH TARGET DEFCONFIG


case $BUILD_BINUTILS in
	yes) $BDIR/build-binutils || exit 101
esac
case $BUILD_GCC in
	yes) $BDIR/build-gcc || exit 102
esac
case $BUILD_KERNEL in
	yes) $BDIR/build-kernel || exit 103
esac

$ECHO -e "  \033[32mOK\033[0m"
