#!/bin/sh

# Copyright (C) 2007-2016 Segher Boessenkool <segher@kernel.crashing.org>
# Released under the terms of the GNU GPL, version 2

BDIR=$( (cd `dirname $0` ; pwd))
. $BDIR/config


$ECHO "================== Primary platforms ========================="
./build "$@" arm
./build "$@" i386
./build "$@" mips
./build "$@" mips64 ip32_defconfig
./build "$@" powerpc ppc6xx_defconfig
./build "$@" powerpc64
./build "$@" sparc
./build "$@" sparc64
./build "$@" x86_64
$ECHO "================== Secondary platforms ======================="
./build "$@" arm64
./build "$@" s390
$ECHO "================== Tertiary platforms ========================"
./build "$@" alpha
./build "$@" arc nsim_700_defconfig
./build "$@" blackfin
./build "$@" c6x
./build "$@" cris
./build "$@" frv
./build "$@" h8300 edosk2674_defconfig
./build "$@" ia64
./build "$@" m32r
./build "$@" m68k
./build "$@" mn10300
./build "$@" nios2
./build "$@" parisc
./build "$@" parisc64 a500_defconfig
./build "$@" riscv32 riscv32_defconfig
./build "$@" riscv64
./build "$@" sh se7750_defconfig
./build "$@" shnommu se7619_defconfig
./build "$@" tilegx
./build "$@" tilepro
./build "$@" xtensa
$ECHO "================== Imaginary platforms ======================="
./build "$@" microblaze


# Not in GCC:
# avr32 (not the same as avr)
# hexagon
# metag
# openrisc
# unicore32

# Removed from GCC:
# score
# sh64
